### ISSUE TITLE
Issue while connecting to obd simulator

### ISSUE THREAD

**Issue by arvindnegi1** [enviroCar/enviroCar-app#413]
## Description of issue
**Logcat**
```
java.io.IOException: bt socket closed, read return: -1
        at android.bluetooth.BluetoothSocket.read(BluetoothSocket.java:558)
        at android.bluetooth.BluetoothInputStream.read(BluetoothInputStream.java:59)
        at org.envirocar.obd.SimulatorService$ConnectedThread.run(SimulatorService.java:361)
```

**Comment by arvindnegi1** [comment]
@dewall sir, i am facing this issue . Can you please guide me how to solve this.

**Comment by dewall** [comment]
@arvindnegi1 I'm missing a lot of details here. What are you doing? What is the way to reproduce?
In general, the bt socket closed error feels sometimes to be quite generic. Maybe with a little bit more information I can give you more details.

**Comment by arvindnegi1** [comment]
**logcat of  obd simulator**
```2020-02-16 01:23:50.246 7973-8206/org.envirocar.obd E/SimulatorService: disconnected
    java.io.IOException: bt socket closed, read return: -1
        at android.bluetooth.BluetoothSocket.read(BluetoothSocket.java:558)
        at android.bluetooth.BluetoothInputStream.read(BluetoothInputStream.java:59)
        at org.envirocar.obd.SimulatorService$ConnectedThread.run(SimulatorService.java:361)
2020-02-16 01:23:49.731 3378-3400/? E/NotificationService: Suppressing notification from package by user request.
2020-02-16 01:23:50.736 3378-3400/? E/NotificationService: Suppressing notification from package by user request.
2020-02-16 01:23:51.744 3378-3400/? E/NotificationService: Suppressing notification from package by user request.
2020-02-16 01:23:52.749 3378-3400/? E/NotificationService: Suppressing notification from package by user request.
2020-02-16 01:23:53.754 3378-3400/? E/NotificationService: Suppressing notification from package by user request.
2020-02-16 01:23:54.758 3378-3400/? E/NotificationService: Suppressing notification from package by user request.
2020-02-16 01:23:57.774 3378-3400/? E/NotificationService: Suppressing notification from package by user request.
2020-02-16 01:23:58.779 3378-3400/? E/NotificationService: Suppressing notification from package by user request.
2020-02-16 01:23:59.315 2761-2911/? E/storaged: getDiskStats failed with result NOT_SUPPORTED and size 0
2020-02-16 01:23:59.784 3378-3400/? E/NotificationService: Suppressing notification from package by user request.
2020-02-16 01:24:00.789 3378-3400/? E/NotificationService: Suppressing notification from package by user request.
2020-02-16 01:24:02.618 4632-7945/? E/ChromeSync: [Sync,SyncIntentOperation] Error handling the intent: Intent { act=android.intent.action.PACKAGE_ADDED dat=package:org.envirocar.obd flg=0x4000010 cmp=com.google.android.gms/.chimera.GmsIntentOperationService (has extras) }.
2020-02-16 01:24:02.800 3378-3400/? E/NotificationService: Suppressing notification from package by user request.
2020-02-16 01:24:03.804 3378-3400/? E/NotificationService: Suppressing notification from package by user request.
```
***logcat of envirocar app**
```
org.envirocar.obd.exception.EngineNotRunningException: No PIDs returned. Possibly the car engine is not running.; StackTrace: 
    	org.envirocar.obd.adapter.SyncAdapter.lambda$initialize$0$SyncAdapter(SyncAdapter.java:119)
    	org.envirocar.obd.adapter.-$$Lambda$SyncAdapter$MIJkgQc3IwCtnIBIGZ724d6DMGc.subscribe(Unknown Source:2)
    	io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
    	io.reactivex.Observable.subscribe(Observable.java:12267)
    	io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
    	io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
    	io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
    	io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
    	java.util.concurrent.FutureTask.run(FutureTask.java:266)
    	java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
    	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    	java.lang.Thread.run(Thread.java:764)
2020-02-16 01:30:14.947 17879-17879/? E/SearchServiceStarter: Task 174 failed or timed out. Client 78634255367316127 disconnecting from SearchService!
    java.util.concurrent.CancellationException: Task was cancelled.
        at com.google.common.t.a.d.c(SourceFile:114)
        at com.google.common.t.a.d.get(SourceFile:74)
        at com.google.common.t.a.dj.a(SourceFile:1)
        at com.google.common.t.a.bu.a(SourceFile:6)
        at com.google.common.t.a.bq.run(SourceFile:4)
        at com.google.android.apps.gsa.shared.util.c.a.bb.run(SourceFile:2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
```
### Steps to reproduce
1. Launch obd-ii simulator.
2. Launch enviroCar app on other phone.
3. Enable bluetooth of both devices.
4. Connect to obd-iisimulator (other phone).
5. Start track.
<h4>Log showing in obd-ii simulator but before starting track its showing device disconnected every time</h4>

@dewall sir, thanks for your quick reply .Sorry sir, i was bit busy with something so forget about this issue to provide full details.

**Comment by arvindnegi1** [comment]
@dewall sir, Please guide me how to solve this whenever you get time. :)

**Comment by dewall** [comment]
thx @arvindnegi1 for pointing on this issue. We had implemented the need for PIDs on the app side, but had not yet integrated in the simulator. I've corrected this right now.
