### ISSUE TITLE
App crash on Create Car

### ISSUE THREAD

**Issue by arvindnegi1** [enviroCar/enviroCar-app#423]
## Description of issue
App crash on launching car selectionaddcar.

**Steps to reproduce** 
1. Open dashboard fragment
2. Click select car option.
3. Click floating action button to add car.
4. App crashes.

**Logcat**
```
 java.lang.NullPointerException: Attempt to invoke virtual method 'int org.envirocar.core.entity.Car$FuelType.hashCode()' on a null object reference
        at org.envirocar.core.entity.CarImpl.hashCode(CarImpl.java:195)
        at java.util.HashMap.hash(HashMap.java:338)
        at java.util.HashMap.put(HashMap.java:611)
        at java.util.HashSet.add(HashSet.java:219)
        at org.envirocar.app.views.carselection.CarSelectionAddCarFragment.addCarToAutocompleteList(CarSelectionAddCarFragment.java:703)
        at org.envirocar.app.views.carselection.CarSelectionAddCarFragment.access$200(CarSelectionAddCarFragment.java:83)
        at org.envirocar.app.views.carselection.CarSelectionAddCarFragment$2.onNext(CarSelectionAddCarFragment.java:404)
        at org.envirocar.app.views.carselection.CarSelectionAddCarFragment$2.onNext(CarSelectionAddCarFragment.java:365)
        at io.reactivex.internal.operators.observable.ObservableFromPublisher$PublisherSubscriber.onNext(ObservableFromPublisher.java:56)
        at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:407)
        at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by arvindnegi1** [comment]
@dewall sir, earlier it was working fine, i was in doubt the my code has done something wrong but when i downloaded app from google play store same issue occurred.

**Comment by arvindnegi1** [comment]
@dewall sir, it showing NullPointerException.

**Comment by dewall** [comment]
@arvindnegi1 thanks for pointing on this issue. We will fix it very soon. A bad and unknown car type has been added to the server (unintentionally).

**Comment by dewall** [comment]
fixed
